version: "3.3"

services:
  db:
    image: mysql:8
    volumes:
      - ./db/.data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 10
  app:
    image: ewajs/eratostenes:latest
    build:
      context: ./app
    volumes:
      - ./app/src:/app/src
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - "80:80"
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - DATABASE_HOST
      - SQLALCHEMY_TRACK_MODIFICATIONS
